- name: APT update & clean
  hosts: all
  tasks:
   - name: Ping hosts
     ansible.builtin.ping:
   - name: Run update_cache
     ansible.builtin.apt:
       update_cache: yes
       cache_valid_time: 3600
   - name: APT Auto remove
     ansible.builtin.apt:
       autoremove: yes
       purge: true
   - name: APT Clean
     apt:
       clean: yes